---
- name: Scheduled tasks
  hosts: all
  become: yes
  tasks:
    - name: Ensure file exists
      file:
        path: /var/log/time.log
        state: touch
        mode: 0644
    - name: Create cronjob fro root user
      cron:
        name: "check time"
        minute: "0"
        user: root
        job: "/usr/bin/date>>/var/log/time.log"


