---
- name: Use Conditionals to Control Play Execution
  hosts: all
  become: yes
  tasks:
    - name: Change vm.swappiness
      sysctl:
        name: vm.swappiness
        value: 10
        state: present
      when: ansible_memtotal_mb >= 2048
    - name: Report not enough memory
      debug:
        msg: "Server memory less than 2048MB. RAM size: {{ ansible_memtotal_mb }}"
      when: ansible_memtotal_mb < 2048
